########################################################
# LOCAL configuration for developing with BMW PROXY
#
# This is an example configuration. Fill in all values and then rename this file to appplication.yml
# DO NOT check in this file into version controll!
# DO NOT expose your passwords

PROXY_ACTIVE: false
PROXY_HOST: proxy-host.internal
PROXY_PORT: 8080
PROXY_USER: proxyUser
PROXY_PASS: XXXXX

# Spring configuration
spring:
  datasource:
    url: jdbc:mysql://host:3306/your_db
    username: dbUser
    password: XXXX

# Liquido WebApp
liquido:

  # The admin uer can login with this secret token. This is used in tests.
  devLoginToken: 123488

  # JSON Web Token secrets
  jwt:
    secret: XXXXX
    expiration: 3600000   # milliseconds

  # Secretes for generation BCRYPT hash values
  bcrypt:
    # A secret only known to the server. This ensures that only this server is able to create valid voterTokens and checksums
    secret: XXXXX
    # SECURITY: Salt for creating checksums of voterTokens. This must be a valid BCrypt salt ie. begin with $2a$10$!
    salt: $2a$10$1XfrrrRTN2Wp3U7QI.JIzu

  # Email SMTP sever for sending out emails.
  smtp:
    host: smtp.server.com
    port: 587
    from: donotreply@domain.tld
    fromname: LIQUIDO
    username: user@server.com
    pass: XXXXXXX

  # Admin user (will automatically be upserted)
  admin:
    email: admin@liquido.de
    name: Liquido Admin
    mobilephone: +491234567890
    picture: /static/img/avatars/Avatar16.png

  # Twilio AUTHY API secrets
  authy:
    apiUrl: http://api.authy.com
    apiKey: XXXXXX

  # liquido request logging
  debug:
    log:
      includeResponsePayload: true

#  slf4j logging, can be configured by package
logging:
  level:
    org:
      doogie:
        liquido: INFO

