# ===================================================================
# LIQUIDO - Spring Boot Application Properties
#
# Settings for TEST
# These overwrite the settings from default application-local.yml
# ===================================================================

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# DO NOT USE THESE SETTINGS IN PROD!  YOU WILL LOSE ALL YOUR DATA!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

graphiql:
  #mapping: /graphiql
  #endpoint: /liquido-api/v3/graphql

# In DEV we let spring JPA automatically generate a database schema.
spring:
  jpa:
    # In TEST We do not let hibernate automatically generate a DB schema. Schema and static test data ("fixtures") will be loaded from sampleDB-H2.sql for tests
    generate-ddl: false
    hibernate:
      ddl-auto: none   # none, validate, update, create-drop (NEVER SET create-drop IN PROD!!! You will loose all your data!!!)

# More logging while tests are running
logging:
  level:
    root: INFO
    web: DEBUG
    #sql: TRACE
    org:
      doogie:
        liquido: DEBUG
      springframework:
        web:
          filter:
            # Show HTTP requests
            CommonsRequestLoggingFilter: DEBUG


liquido:
  # Load prepared test data for TEST. SQL FILE MUST HAVE BEEN CREATED BEFORE!
  test:
    recreateTestData: false
    loadTestData: true
    sampleDbFile: ./example-data/sampleDB-H2.sql
