@startuml

autonumber

actor User
participant LiquidoApp
participant "Liquido Backend" as BE
participant AuthyAPI
participant AuthyApp

User -> LiquidoApp: Open App

LiquidoApp -> BE: Request\nOne-Time-Token\n(OTT)

BE -> AuthyAPI: ""GET https://api.authy.com/protected/json/sms/{AUTHY_ID}""
AuthyAPI -> AuthyApp: push notification

note right of AuthyApp: Show OTT to user

User -> LiquidoApp: user enters OTT\nfrom AuthyApp

LiquidoApp -> BE: login with OTT
BE -> AuthyAPI: ""GET https://api.authy.com/protected/json/verify/{TOKEN}/{AUTHY_ID}""
AuthyAPI --> BE: HTTP 200

BE --> LiquidoApp: JsonWebToken (JWT)
LiquidoApp --> User: login successful

LiquidoApp -> BE: authenticated requests\nwith JWT in header
BE --> LiquidoApp: OK


@enduml